### PR TITLE
Slash commands

### PR DESCRIPTION
**Pull request by OoLunar**
This shows examples on how to
- Set up slash commands
- Use slash commands
- Add arguments to slash commands
- Add optional arguments to slash commands
- Use group slash commands
- Shows how to use the "Bot is thinking" response type
- Enums in arguments
- Discord entities in arguments
- The choice attribute
- The choice provider interface/attribute

What this doesn't showcase yet:
~~- Slash command permissions (when they get released into [Nuget](https://www.nuget.org/packages/IDoEverything.DSharpPlus.SlashCommands))~~
~~- Property Injection demonstration. Waiting until that's released into Nuget.~~

Merged since property injection and role/user permissions won't be included into the library anytime soon.

### CODE REVIEW

**Comment by Lulalaby** [comment]
Great!

**Review by Lulalaby — COMMENTED** [review]
For now it's cool!
I'll take a close look the next days. 
Thank you <3

**Comment by OoLunar** [comment]
Awesome. I'll get started on VNext soon

**Comment by Lulalaby** [comment]
Perfect :3

**Comment by OoLunar** [comment]
I'm going to go ahead and merge this now since property injection and role/user permissions won't be included into the library anytime soon.

**Comment by Lulalaby** [comment]
That's amazing!

**Pull request merged**
